services:
  app:
    image: php:8.3-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"


