services:
  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    container_name: app
    volumes:
      - ./:/var/www
      - /var/www/vendor/

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:9.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  npm:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: npm
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    tty: true
    ports:
      - "8081:8081"

volumes:
  db_data:
